"use strict";
// Verify the published case against the frozen source and the analysis it opens.
const assert = require("node:assert/strict"), fs = require("node:fs"), vm = require("node:vm");
const source = name => fs.readFileSync(require.resolve("../dist/" + name), "utf8");
const demo = require("../dist/data/demo.json");
const ctx = vm.createContext({ console, demo, document: { getElementById() { return { textContent: "" }; } } });
const run = code => vm.runInContext(code, ctx);
const app = source("app.js"), lab = source("lab.js"), workspace = source("workspace.js");
run(app.slice(0, app.indexOf('document.querySelectorAll(".mode-button").forEach((button) => button.addEventListener')));
run(lab.slice(lab.indexOf("function sectorChecks()"), lab.indexOf("function updateLabDetails()")));
run(workspace.slice(workspace.indexOf("function selectionMetrics("), workspace.indexOf("function renderSelection(")));
run(`renderDistancePerformanceAnalysis=()=>{};
  state.selectedA=4; state.selectedB=81; state.session=demo.session;
  state.replayData=new Map([4,81].map(id=>[id,demo.datasets.find(d=>d.lap.driver_number===id&&d.lap.lap_number===25)]));
  buildDistancePerformanceAnalysis();`);
const a = demo.datasets.find(d => d.lap.driver_number === 4 && d.lap.lap_number === 25).lap;
const b = demo.datasets.find(d => d.lap.driver_number === 81 && d.lap.lap_number === 25).lap;
assert.equal((a.lap_duration - b.lap_duration).toFixed(3), "-0.131");
const sectors = run("sectorChecks()");
assert.deepEqual(Array.from(sectors, r => r.sectorDelta.toFixed(3)), ["-0.090", "-0.038", "-0.003"]);
assert.equal(sectors[0].residual.toFixed(3), "0.045");
const metrics = run("[state.distanceAnalysis.lapA,state.distanceAnalysis.lapB].map(lap=>selectionMetrics(lap,.136,.272))");
assert.deepEqual(Array.from(metrics, m => m.minimum.speed), [98, 93]);
assert.deepEqual(Array.from(metrics, m => Array.from(m.throttle, p => (p*100).toFixed(2))), [["18.71", "19.00"], ["18.68", "18.94"]]);
assert.ok(Math.max(...metrics.map(m => m.throttle[0])) <= Math.min(...metrics.map(m => m.throttle[1])));
assert.equal(run("localDeltaRangeSupported(state.distanceAnalysis.lapA,state.distanceAnalysis.lapB,.136,.272)"), false);
const old = [4,81].map(id => demo.datasets.find(d => d.lap.driver_number === id && d.lap.lap_number === 22).lap);
assert.equal((old[0].lap_duration-old[1].lap_duration).toFixed(3), "0.658");
console.log("Featured case passed: reported timing, minimum speeds, overlapping throttle brackets, unavailable local delta and contrary lap 22.");
