"use strict";
const assert=require('node:assert/strict'),P=require('../dist/pace-engine.js');
const start=Date.parse('2025-05-01T10:00:00Z');
function data(){return {session:{session_type:'Practice'},laps:Array.from({length:8},(_,i)=>({driver_number:4,lap_number:i+1,date_start:new Date(start+i*100000).toISOString(),lap_duration:90+i*.1})),stints:[{driver_number:4,stint_number:1,lap_start:1,lap_end:8,tyre_age_at_start:0,compound:'MEDIUM'}],raceControl:[{date:new Date(start).toISOString(),scope:'Track',flag:'GREEN',message:'GREEN FLAG'}],pits:[]};}
const d=data(),p=P.prepare(d),f=P.forecast(p,4,4);
assert.equal(f.n,3);assert.deepEqual(f.used,[2,3,4]);assert.ok(Math.abs(f.recent[0].value-90.2)<1e-9);
assert.ok(Math.abs(f.trend[0].value-90.4)<1e-9);
assert.equal(P.forecast(p,4,1).n,1);assert.equal(P.forecast(p,4,1).trend[0].value,null);
assert.equal(P.forecast(p,4,1).recent[0].value,null,'One lap is only an observed reference, not a forecast');
assert.equal(P.forecast(p,4,0).reason,'missing_origin');
const changed=data();changed.laps.filter(l=>l.lap_number>4).forEach(l=>{l.lap_duration=10;});
assert.deepEqual(P.forecast(P.prepare(changed),4,4),f,'Later laps cannot alter an earlier forecast');
const offset=P.forecast(p,4,4,{offset:-.5});assert.equal(offset.recent[0].value,f.recent[0].value-.5);
const negative=data();negative.laps.forEach((l,i)=>{l.lap_duration=95-i;});
const neg=P.forecast(P.prepare(negative),4,4);assert.equal(neg.trend[0].value,null);assert.equal(neg.recent[0].value,93);
const unknownAge=data();unknownAge.stints[0].tyre_age_at_start=null;
assert.equal(P.forecast(P.prepare(unknownAge),4,4).recent[0].value,f.recent[0].value);
assert.equal(P.forecast(P.prepare(unknownAge),4,4).trend[0].reason,'missing_tyre_age');
const red=data();red.raceControl.push({date:new Date(start+250000).toISOString(),scope:'Track',flag:'RED',message:'RED FLAG'});
assert.equal(P.forecast(P.prepare(red),4,4).reason,'affected_track_status');
const unknown=data();unknown.raceControl=[];assert.equal(P.forecast(P.prepare(unknown),4,4).reason,'unknown_track_status');
const opening=data();opening.raceControl=[{date:new Date(start).toISOString(),message:'GREEN LIGHT - PIT EXIT OPEN'}];
assert.equal(P.forecast(P.prepare(opening),4,4).reason,null,'Non-race opening without a flag is explicitly inferred');
opening.session.session_type='Race';assert.equal(P.forecast(P.prepare(opening),4,4).reason,'unknown_track_status','Pit opening must not start a race');
const finish=data();finish.raceControl.push({date:new Date(start+370000).toISOString(),scope:'Track',flag:'CHEQUERED',message:'CHEQUERED FLAG'});
assert.equal(P.prepare(finish).reason(finish.laps[3]),null,'A lap already underway can finish after the chequered flag');
assert.equal(P.forecast(P.prepare(finish),4,4).reason,'session_finished','No continued-run forecast after the phase has finished');
const swap=data();swap.stints.push({driver_number:4,stint_number:2,lap_start:4,lap_end:8,tyre_age_at_start:0,compound:'SOFT'});
const pitExit=data();pitExit.laps[0].is_pit_out_lap=true;pitExit.pits=[{driver_number:4,lap_number:1,date:new Date(start+100).toISOString()}];
assert.equal(P.forecast(P.prepare(pitExit),4,2).reason,null,'A pit-exit event must not remove the following flying lap');
const incomplete=data();incomplete.laps[3].duration_sector_3=null;assert.equal(P.forecast(P.prepare(incomplete),4,4).reason,'incomplete_sector_timing');
assert.deepEqual(P.forecast(P.prepare(swap),4,4).used,[4]);
const {audit}=require('../tools/audit_all_sessions.cjs');
d.session={session_key:1,meeting_key:1,year:2025,session_name:'Practice 1',session_type:'Practice'};
const a=audit(d);assert.ok(a.available>0);assert.equal(a.origins,a.available+Object.values(a.withheld).reduce((s,n)=>s+n,0));
const slow=data();slow.laps[4].lap_duration=110;assert.equal(P.prepare(slow).reason(slow.laps[4]),null,'Slow future outcome must not be hidden');
console.log('All-session pace checks passed: short-run reference, trend, missing age, pit/flag gates, independent offset and no future fit leakage.');
