const assert=require('node:assert/strict'),E=require('../dist/race-engine.js');
const vegas=require('../dist/data/race-demo.json'),austin=require('../dist/data/race-austin.json');
const inputs={...require('./race_fixtures.cjs').inputs,compoundA:'MEDIUM',compoundB:'HARD',warmupA:.6,warmupB:.6};
const s=E.snapshot(austin,austin.cutoff,inputs.fuelGain),v=E.snapshot(vegas,vegas.cutoff,inputs.fuelGain),r=E.evaluate(s,1,44,inputs);
assert.equal(s.control.status,'GREEN');assert.equal(v.control.status,'GREEN_INFERRED');
assert.ok(v.rows.reduce((n,r)=>n+r.models.reduce((n,m)=>n+m.n,0),0)>500);
assert.equal(E.controlAt(vegas.raceControl,Infinity).status,'FINISHED');
assert.equal(E.controlAt([{date:'2023-01-01',flag:'RED',scope:'Track',message:'RED FLAG'}],Infinity).status,'RED');
assert.equal(r.scenarios.filter(x=>!x.unavailable).length,3);
const a=r.a,b=r.b,base=E.simulatePair(a,b,inputs,0,3),aligned=E.simulatePair(a,{...b,lastLap:a.lastLap},inputs,0,3);
assert.ok(Math.abs(base.finishGap-aligned.finishGap)<1e-10);
const swapped=E.simulatePair(b,a,{...inputs,compoundA:'HARD',compoundB:'MEDIUM'},3,0);
assert.ok(Math.abs(base.finishGap+swapped.finishGap)<1e-10);
const pit=E.simulatePair(a,b,{...inputs,pitLoss:35},0,3),warm=E.simulatePair(a,b,{...inputs,warmupA:1.6},0,3);
assert.ok(Math.abs(base.finishGap-pit.finishGap)<1e-10);assert.ok(Math.abs(warm.finishGap-base.finishGap-1)<1e-10);
assert.ok(Math.abs(pit.points[1].gap-base.points[1].gap-13)<1e-10);
assert.equal(E.fitInterval(E.contrastWeights(base.weights,base.weights)),0);
assert.ok(r.comparisons[0].fitHalfWidth<base.fitHalfWidth);
assert.ok(Math.abs(r.comparisons[0].delta)<r.comparisons[0].fitHalfWidth);
assert.equal(E.supported({...a.pace,slope:-.1},a.pace.maxAge+1),false);
assert.equal(E.supported(a.pace,a.pace.maxAge+6),false);
const future=structuredClone(austin);future.raceControl.push({date:new Date(austin.cutoff+1000).toISOString(),scope:'Track',flag:'RED'});
assert.deepEqual(E.snapshot(future,austin.cutoff,inputs.fuelGain),s);
const sec=n=>new Date(1700000000000+n*1000).toISOString();
const exposure=E.trafficExposure([{date:sec(0),driver_number:1,interval:2},{date:sec(10),driver_number:1,interval:1},{date:sec(11),driver_number:1,interval:3}],1,Date.parse(sec(0)),Date.parse(sec(20)));
assert.ok(Math.abs(exposure.fraction-.05)<1e-10);
assert.equal(E.trafficExposure([{date:sec(0),driver_number:1,interval:0}],1,Date.parse(sec(0)),Date.parse(sec(10))).fraction,0);
console.log(JSON.stringify({checks:'passed',vegasModels:v.rows.filter(r=>r.models.length).length,vegasFitLaps:v.rows.reduce((n,r)=>n+r.models.reduce((n,m)=>n+m.n,0),0),austin:r.scenarios.map(x=>({id:x.id,gap:x.finishGap,fitHalfWidth:x.fitHalfWidth})),paired:r.comparisons},null,2));
