"use strict";
const assert=require("node:assert/strict");
const path=require("node:path");
const {chromium}=require("playwright");
(async()=>{
  const browser=await chromium.launch({headless:true,channel:process.env.LAB_BROWSER||"chrome"});
  const page=await browser.newPage({viewport:{width:1440,height:1000}}), errors=[];
  page.on("pageerror",e=>errors.push(e.message));
  try {
    await page.goto(process.env.LAB_URL||"http://127.0.0.1:4173/");
  await page.locator("#load-demo").click();
    await page.waitForFunction(()=>state.source==="demo"&&linkedTraceActive());
    assert.match(await page.locator("#result-overview").textContent(),/NOR.*0.131/);
    assert.match(await page.locator("#trace-quality-note").textContent(),/S1 \+0.045/);
    assert.ok((await page.locator("#linked-delta-path").getAttribute("d")).includes("M"));
    const beforeMap=await page.locator("#car-marker-a").getAttribute("cx");
    const box=await page.locator("#speed-chart").boundingBox();
    await page.mouse.move(box.x+box.width*.3,box.y+box.height*.5);
    assert.match(await page.locator("#speed-tooltip").textContent(),/X 30.0%/);
    for(const id of ["speed-cursor","input-cursor","brake-cursor","linked-delta-cursor"]) assert.ok(Math.abs(Number(await page.locator("#"+id).getAttribute("x1"))-300)<1);
    assert.notEqual(await page.locator("#car-marker-a").getAttribute("cx"),beforeMap);
    await page.mouse.move(box.x+box.width*.25,box.y+30);await page.mouse.down();await page.mouse.move(box.x+box.width*.32,box.y+30,{steps:8});await page.mouse.up();
    const range=await page.evaluate(()=>state.progressWindow);
    assert.ok(Math.abs(range[0]-.25)<.002&&Math.abs(range[1]-.32)<.002);
    const chartWidths=await page.evaluate(()=>["speed-chart","input-chart","brake-chart","linked-delta-chart"].map(id=>{const b=document.getElementById(id).getBoundingClientRect();return [b.x,b.width];}));
    assert.ok(chartWidths.every(([x,w])=>Math.abs(x-chartWidths[0][0])<1&&Math.abs(w-chartWidths[0][1])<1),"All four charts share physical x bounds");
    assert.ok((await page.locator("#track-selection").getAttribute("d")).length>10);
    assert.match(await page.locator("#selection-results").textContent(),/First brake onset bracket/);
    await page.locator("#brake-chart").focus();await page.keyboard.press("ArrowRight");
    assert.ok(await page.locator("#brake-tooltip").isVisible());
    await page.keyboard.press("Escape");
    assert.deepEqual(await page.evaluate(()=>state.progressWindow),[0,1]);
    await page.locator("#focus-largest-sector").click();
    assert.ok(await page.evaluate(()=>Math.abs(state.progressWindow[1]-sectorChecks()[0].progressA)<1e-10));
    await page.locator("#range-from").fill("25");await page.locator("#range-to").fill("32");await page.locator("#apply-range").click();
    assert.deepEqual(await page.evaluate(()=>state.progressWindow),[.25,.32]);
    const metrics=await page.evaluate(()=>selectionMetrics(state.distanceAnalysis.lapA,.25,.32));
    assert.ok(metrics.count>0&&Number.isFinite(metrics.minimum.speed));
    await page.locator(".dashboard-grid").screenshot({path:path.join(process.env.TEMP||".","performance-lab-linked.png")});
    await page.locator("#reset-range").click();
    const support=await page.evaluate(()=>({masked:state.distanceAnalysis.grid.filter(p=>p.delta===null).length,bad:observedAt([{progress:0,t:0,speed:100},{progress:1,t:5,speed:300}],.5,"speed"),fit:state.paceRows.filter(r=>r.usable===2).map(r=>({r2:r.r2,status:r.fitStatus}))}));
    assert.ok(support.masked>2);assert.equal(support.bad,null);assert.ok(support.fit.length>0);assert.ok(support.fit.every(r=>r.r2===null&&r.status==="limited_laps"));
    await page.locator("#tab-stints").click();
    assert.match(await page.locator("#stint-table-body").textContent(),/2 laps · limited interpretation/);
    assert.doesNotMatch(await page.locator("#stint-table-body").textContent(),/R² 1.00/);
    await page.locator("#tab-case").click();
    assert.match(await page.locator("#case-content").textContent(),/direction reverses/);
    await page.locator('.case-pair[data-pair="22"]').click();
    assert.match(await page.locator("#result-overview").textContent(),/PIA.*0.658/);
    assert.match(await page.locator("#focus-largest-sector").textContent(),/S3 \+0.305/);
    await page.locator("#focus-largest-sector").click();
    assert.equal((await page.evaluate(()=>state.progressWindow))[1],1);
    await page.locator("#tab-case").click();await page.locator('.case-pair[data-pair="25"]').click();
    await page.locator("#axis-time").click();
    assert.equal(await page.locator("#linked-delta-chart").isVisible(),false);
    assert.match(await page.locator("#trace-help").textContent(),/equal seconds are not equal/);
    await page.locator("#axis-progress").click();
    assert.equal(await page.locator("#language-toggle").count(), 0);
    assert.match(await page.locator("#result-overview").textContent(),/quicker in this pair/);
    await page.locator("#tab-stints").click();assert.match(await page.locator("#stint-table-body").textContent(),/2 laps · limited interpretation/);
    await page.locator("#tab-case").click();assert.match(await page.locator("#case-content").textContent(),/The direction reverses/);
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);
    await page.locator("#range-from").fill("20");await page.locator("#range-to").fill("30");await page.locator("#apply-range").click();
    assert.deepEqual(await page.evaluate(()=>state.progressWindow),[.2,.3]);
    await page.locator("#speed-chart").scrollIntoViewIfNeeded();
    await page.screenshot({path:path.join(process.env.TEMP||".","performance-lab-linked-mobile.png")});
    await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>document.documentElement.style.fontSize="200%");
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,"No page overflow at 200% text size");
    assert.deepEqual(errors,[]);
    console.log(JSON.stringify({result:"linked workspace checks passed",support,range,chartWidths,errors},null,2));
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
